captainVersion: "4"
caproverOneClickApp:
  description: "authentik is an open-source Identity Provider focused on flexibility and versatility. You can use authentik in an existing environment to add support for new protocols."
  instructions:
    start: Install authentik and start using it.
    end: Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of authentik. See ghcr.io/goauthentik/server
      defaultValue: 2022.7.2
      label: App Version
    - id: $$cap_postgres_version
      label: Postgres (database) version
      defaultValue: "14"
      description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres?tab=tags
    - id: $$cap_db_db
      label: database name
      defaultValue: authentik
      description: Name of the database.
    - id: $$cap_db_pass
      label: database password
      defaultValue: $$cap_gen_random_hex(16)
      description: Password for the database user and root using mysql.
      validRegex: /.{1,}/
    - id: $$cap_app_log_level
      label: App Log Level
      defaultValue: "info"
      description: Log level for the app.
    - id: $$cap_db_user
      label: database user
      defaultValue: authentik
      description: Username for the database using postgres.
    - id: $$cap_email_from
      label: Email From Address
      description: Configures the global From header whilst sending emails
    - id: $$cap_email_server_user
      label: Email Server User
      defaultValue: ""
      description: Mail server user
    - id: $$cap_email_server_password
      label: Email Server Password
      defaultValue: ""
      description: Mail server password
    - id: $$cap_email_server_host
      label: Email Server Host
      defaultValue: ""
      description: Mail server host
    - id: $$cap_email_server_port
      label: Email Server Port
      defaultValue: 587
      description: Mail server port
    - id: $$cap_email_use_tls
      label: Email Use TLS
      defaultValue: true
      description: Use TLS for email
    - id: $$cap_email_use_ssl
      label: Email Use SSL
      defaultValue: false
      description: Use SSL for email
    - id: $$cap_email_timeout
      label: Email Timeout
      defaultValue: 10
      description: Timeout for email
    - id: $$cap_app_geoip_account_id
      label: GeoIP Account ID
      defaultValue: ""
      description: GeoIP account ID
    - id: $$cap_app_geoip_license_key
      label: GeoIP License Key
      defaultValue: ""
      description: GeoIP license key
  displayName: authentik
  isOfficial: false
  documentation: "https://github.com/goauthentik/authentik"
services:
  $$cap_appname:
    image: ghcr.io/goauthentik/server:$$cap_app_version
    volumes:
      - $$cap_appname-media:/media
      - $$cap_appname-custom-templates:/templates
      - geoip:/geoip
    environment:
      AUTHENTIK_SECRET_KEY: "$$cap_app_secret_key"
      AUTHENTIK_REDIS__HOST: srv-captain--$$cap_appname-redis
      AUTHENTIK_POSTGRESQL__HOST: srv-captain--$$cap_appname-db
      AUTHENTIK_POSTGRESQL__USER: $$cap_db_user
      AUTHENTIK_POSTGRESQL__NAME: $$cap_db_db
      AUTHENTIK_POSTGRESQL__PASSWORD: $$cap_db_pass
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST: $$cap_email_server_host
      AUTHENTIK_EMAIL__PORT: $$cap_email_server_port
      # Optionally authenticate (don't add quotation marks to you password)
      AUTHENTIK_EMAIL__USERNAME: $$cap_email_user
      AUTHENTIK_EMAIL__PASSWORD: $$cap_email_password
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS: $$cap_email_use_tls
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL: $$cap_email_use_ssl
      AUTHENTIK_EMAIL__TIMEOUT: $$cap_email_timeout
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM: $$cap_email_from
      GEOIPUPDATE_ACCOUNT_ID: $$cap_app_geoip_account_id
      GEOIPUPDATE_LICENSE_KEY: $$cap_app_geoip_license_key
      AUTHENTIK_AUTHENTIK__GEOIP: /geoip/GeoLite2-City.mmdb
      AUTHENTIK_LOG_LEVEL: $$cap_app_log_level
    caproverExtra:
      containerHttpPort: "9000"
  $$cap_appname-worker:
    image: ghcr.io/goauthentik/server:$$cap_app_version
    command: worker
    volumes:
      - $$cap_appname-media:/media
      - $$cap_appname-custom-templates:/templates
      - geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock
      - $$cap_appname-certs:/certs
    environment:
      AUTHENTIK_SECRET_KEY: "$$cap_app_secret_key"
      AUTHENTIK_REDIS__HOST: srv-captain--$$cap_appname-redis
      AUTHENTIK_POSTGRESQL__HOST: srv-captain--$$cap_appname-db
      AUTHENTIK_POSTGRESQL__USER: $$cap_db_user
      AUTHENTIK_POSTGRESQL__NAME: $$cap_db_db
      AUTHENTIK_POSTGRESQL__PASSWORD: $$cap_db_pass
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST: $$cap_email_server_host
      AUTHENTIK_EMAIL__PORT: $$cap_email_server_port
      # Optionally authenticate (don't add quotation marks to you password)
      AUTHENTIK_EMAIL__USERNAME: $$cap_email_user
      AUTHENTIK_EMAIL__PASSWORD: $$cap_email_password
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS: $$cap_email_use_tls
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL: $$cap_email_use_ssl
      AUTHENTIK_EMAIL__TIMEOUT: $$cap_email_timeout
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM: $$cap_email_from
      GEOIPUPDATE_ACCOUNT_ID: $$cap_app_geoip_account_id
      GEOIPUPDATE_LICENSE_KEY: $$cap_app_geoip_license_key
      AUTHENTIK_AUTHENTIK__GEOIP: /geoip/GeoLite2-City.mmdb
      AUTHENTIK_LOG_LEVEL: $$cap_app_log_level
  $$cap_appname-db:
    documentation: Taken from https://hub.docker.com/_/postgres
    image: postgres:$$cap_postgres_version
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: $$cap_db_pass
      POSTGRES_DB: $$cap_db_db
      POSTGRES_USER: $$cap_db_user
    caproverExtra:
      notExposeAsWebApp: "true"
  $$cap_appname-redis:
    image: redis:7
    volumes:
      - $$cap_appname-redis:/data
