captainVersion: 4
services:
  $$cap_appname:
    image: dgtlmoon/changedetection.io:$$cap_version
    environment:
      BASE_URL: https://$$cap_appname.$$cap_root_domain
      PLAYWRIGHT_DRIVER_URL: http://srv-captain--$$cap_appname-playwright:3000
      WEBDRIVER_URL: http://srv-captain--$$cap_appname-webdriver:3000
    volumes:
      - "$$cap_appname-data:/datastore"
    caproverExtra:
      containerHttpPort: "5000"
  $$cap_appname-webdriver:
    image: selenium/standalone-chrome-debug:$$cap_selenium_version
    environment:
      VNC_NO_PASSWORD: 1
      SCREEN_WIDTH: $$cap_screen_width
      SCREEN_HEIGHT: $$cap_screen_height
      SCREEN_DEPTH: $$cap_screen_depth
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    restart: unless-stopped
    caproverExtra:
      notExposeAsWebApp: "true"
    # Used for fetching pages via Playwright+Chrome where you need Javascript support.

  $$cap_appname-playwright:
    image: browserless/chrome:$$cap_playwright_version
    restart: unless-stopped
    environment:
      SCREEN_WIDTH: $$cap_screen_width
      SCREEN_HEIGHT: $$cap_screen_height
      SCREEN_DEPTH: $$cap_screen_depth
      ENABLE_DEBUGGER: false
      PREBOOT_CHROME: true
      CONNECTION_TIMEOUT: 300000
      MAX_CONCURRENT_SESSIONS: 10
      CHROME_REFRESH_TIME: 600000
      DEFAULT_BLOCK_ADS: $$cap_block_ads
      DEFAULT_STEALTH: $$cap_stealth
    caproverExtra:
      notExposeAsWebApp: "true"
caproverOneClickApp:
  variables:
    - id: $$cap_version
      label: ChangeDetection.io version
      defaultValue: 0.39.3
      description: "Check out their docker page for the valid tags https://hub.docker.com/r/dgtlmoon/changedetection.io/tags"
    - id: $$cap_selenium_version
      label: Selenium version
      defaultValue: 3.141.59
      description: "Check out their docker page for the valid tags https://hub.docker.com/r/selenium/standalone-chrome-debug/tags"
    - id: $$cap_playwright_version
      label: Playwright version
      defaultValue: 1-puppeteer-15.5.0-slim
      description: "Check out their docker page for the valid tags https://hub.docker.com/r/browserless/chrome/tags"
    - id: $$cap_screen_width
      label: Screen width
      defaultValue: 1920
      description: "The width of the screen to use when running the Selenium container"
    - id: $$cap_screen_height
      label: Screen height
      defaultValue: 1080
      description: "The height of the screen to use when running the Selenium container"
    - id: $$cap_screen_depth
      label: Screen depth
      defaultValue: 16
      description: "The depth of the screen to use when running the Selenium container"
    - id: $$cap_block_ads
      label: Block ads
      defaultValue: true
      description: "Whether to block ads when running the Selenium container"
    - id: $$cap_stealth
      label: Stealth
      defaultValue: true
      description: "Whether to stealth when running the Selenium container"
  instructions:
    start: >-
      Self-hosted website change detection monitoring. 
      For more info visit https://github.com/dgtlmoon/changedetection.io
    end: |-
      ChangeDetection.io has been successfully deployed!
      App is available as http://$$cap_appname.$$cap_root_domain.
      Don't forget to use Caprover's HTTP Basic Auth to protect your app.
  displayName: ChangeDetection.io
  isOfficial: false
  description: >-
    ChangeDetection.io is the self-hosted website change detection monitoring.
  documentation: >-
    This docker-compose is taken from https://github.com/dgtlmoon/changedetection.io
