captainVersion: "4"
caproverOneClickApp:
  description: "CloudBeaver is a web server which provides rich web interface."
  instructions:
    start: Install cloudbeaver and start using it.
    end: Please don't forget to turn on SSL after the installation.
  variables:
    - id: $$cap_app_version
      description: Version of cloudbeaver. See https://hub.docker.com/r/dbeaver/cloudbeaver/tags for available versions.
      defaultValue: latest
      label: App Version
    - id: $$cb_admin_pass
      description: Password for the admin user
      defaultValue: $$cap_gen_random_hex(16)
      label: Admin Password
    - id: $$cb_admin_name
      description: Name for the admin user
      defaultValue: admin
      label: Admin Name
    - id: $$cb_server_name
      description: Name for the server
      defaultValue: CloudBeaver
      label: Server Name
  displayName: cloudbeaver
  isOfficial: false
  documentation: See https://cloudbeaver.io/docs/
services:
  $$cap_appname:
    image: dbeaver/cloudbeaver:$$cap_app_version
    volumes:
      - $$cap_appname-data:/data/cloudbeaver
      - $$cap_appname-logs:/opt/cloudbeaver/logs
      - $$cap_appname-workspace:/opt/cloudbeaver/workspace
    environment:
      CB_ADMIN_NAME: $$cb_admin_name
      CB_ADMIN_PASSWORD: $$cb_admin_pass
      CB_SERVER_NAME: $$cb_server_name
      CB_SERVER_URL: https://$$cap_appname.$$cap_root_domain
    caproverExtra:
      containerHttpPort: "8978"
