captainVersion: 4
caproverOneClickApp:
  variables:
    - id: $$cap_elasticsearch_version
      label: Elasticsearch Version Tag
      description: "Check out the releases overview: https://www.elastic.co/de/downloads/elasticsearch"
      defaultValue: 8.5.0
      validRegex: /^([^\s^\/])+$/
    - id: $$cap_elasticsearch_heap_size
      label: Elasticsearch Heap Size
      description: "The heap size of the Elasticsearch container. Must be a number followed by m(egabyte) or g(igabyte), e.g. 256m or 1g"
      defaultValue: "256m"
      validRegex: /^(\d+[mg])$/
    - id: $$cap_elasticsearch_discovery_type
      label: Elasticsearch Discovery Type
      description: "The discovery type of the Elasticsearch container"
      defaultValue: "single-node"
    - id: $$cap_elastic_password
      label: Elasticsearch Password
      description: "The password of the elastic user"
      defaultValue: $$cap_gen_random_hex(16)

  instructions:
    start: 'Elasticsearch is a distributed, RESTful search and analytics engine. This image can be used for single nodes and cluster setups. IMPORTANT: Be sure to extend the virtual memory on all your hosts! (increase "echo ''vm.max_map_count=262144'' >> /etc/sysctl.conf" and restart "sysctl -p")'
    end: 'Deployment of Elasticsearch is finished. You might see 502 errors for the next 2 minutes. Goto <YOUR-APP-URL>/_cat/health to check the health of your cluster. IMPORTANT: Be sure to extend the virtual memory on all your hosts! (increase "echo ''vm.max_map_count=262144'' >> /etc/sysctl.conf" and restart "sysctl -p")'
  displayName: Elasticsearch
  isOfficial: false
  description: Elasticsearch is a search engine based on the Lucene library
  documentation: Look at https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html for further assistance using Elasticsearch with docker.

services:
  $$cap_appname:
    image: docker.elastic.co/elasticsearch/elasticsearch:$$cap_elasticsearch_version
    volumes:
      - $$cap_appname-elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms$$cap_elasticsearch_heap_size -Xmx$$cap_elasticsearch_heap_size"
      discovery.type: $$cap_elasticsearch_discovery_type
      ELASTIC_PASSWORD: $$cap_elastic_password
      xpack.security.enabled: true
    caproverExtra:
      containerHttpPort: 9200
