captainVersion: "4"
caproverOneClickApp:
  description: ""
  instructions:
    start: Install etcd and start using it.
    end: Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of etcd. See https://quay.io/repository/coreos/etcd?tab=tags&tag=latest
      defaultValue: v3.5.6
      label: App Version
  displayName: etcd
  isOfficial: false
  documentation: ""
services:
  $$cap_appname:
    image: quay.io/coreos/etcd:$$cap_app_version
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - $$cap_appname-data:/etcd-data
    environment: []
    caproverExtra:
      containerHttpPort: "2379"
