captainVersion: "4"
services:
  $$cap_appname:
    image: codenotary/immudb:$$cap_app_version
    volumes:
      - $$cap_appname-data:/var/lib/immudb
    environment:
      - IMMUDB_WEB_SERVER_PORT=8080
      - IMMUDB_WEB_SERVER=$$cap_immudb_web_server
      - IMMUDB_PGSQL_SERVER_PORT=5432
      - IMMUDB_PGSQL_SERVER=$$cap_immudb_pgsql_server
      - IMMUDB_ADDRESS=0.0.0.0
      - IMMUDB_ADMIN_PASSWORD=$$cap_immudb_admin_password
      - IMMUDB_AUTH=true
      - IMMUDB_PORT=3322
      - IMMUDB_S3_ACCESS_KEY_ID=$$cap_immudb_s3_access_key_id
      - IMMUDB_S3_SECRET_KEY=$$cap_immudb_s3_secret_key
      - IMMUDB_S3_ENDPOINT=https://b0c2.va12.idrivee2-9.com
      - IMMUDB_S3_BUCKET_NAME=$$cap_immudb_s3_bucket_name
      - IMMUDB_S3_STORAGE=$$cap_immudb_s3_storage
    ports:
      - 3322:3322
      - 5432:5432
    caproverExtra:
      containerHttpPort: "8080"
caproverOneClickApp:
  description: "immudb is a database written in Go, but unlike other databases, it is immutable: history is preserved and can't be changed without clients noticing."
  instructions:
    start: Install immudb and start using it.
    end: Have fun! Consider enabling https and open ports for 3322 (3322) and 5432 (5432).
  variables:
    - id: $$cap_app_version
      description: Version of immudb. See https://hub.docker.com/r/codenotary/immudb/tags for available versions.
      defaultValue: 1.4.1-bullseye-slim
      label: App Version
    - id: $$cap_admin_password
      description: Admin password
      defaultValue: $$cap_gen_random_hex(16)
      label: Admin Password
    - id: $$cap_immudb_web_server
      description: Enable immudb web server
      defaultValue: true
      label: immudb Web Server
      validRegex: /^true|false$/
    - id: $$cap_immudb_pgsql_server
      description: Enable immudb pgsql server
      defaultValue: true
      label: immudb Pgsql Server
      validRegex: /^true|false$
    - id: $$cap_immudb_s3_access_key_id
      description: S3 access key id
      label: S3 Access Key Id
    - id: $$cap_immudb_s3_secret_key
      description: S3 secret key
      label: S3 Secret Key
    - id: $$cap_immudb_s3_endpoint
      description: S3 endpoint
      defaultValue: https://immudb.s3.amazonaws.com
      label: S3 Endpoint
    - id: $$cap_immudb_s3_bucket_name
      description: S3 bucket name
      defaultValue: immudb
      label: S3 Bucket Name
    - id: $$cap_immudb_s3_storage
      description: S3 storage
      defaultValue: false
      label: S3 Storage
      validRegex: "/^(true|false)$/"
  displayName: immudb
  isOfficial: false
  documentation: "https://docs.immudb.io/master/"
