captainVersion: "4"
caproverOneClickApp:
  description:
    "JetBrains Hub is a web-based application that provides user authorization, SSO, centralized information management,
    and dashboards for your activity."
  instructions:
    start: "Select the version you want to install."
    end: "Have fun!"
  variables:
    - id: $$cap_hub_version
      label: "JetBrains Hub version"
      description: "JetBrains Hub version. See https://hub.docker.com/r/jetbrains/hub/tags for more information."
      defaultValue: "2022.1.14638"
  displayName: jetbrains-hub
  isOfficial: false
  documentation: "See https://www.jetbrains.com/help/hub/Introduction-to-HUB.html"
services:
  $$cap_appname:
    image: "jetbrains/hub:$$cap_hub_version"
    volumes:
      - $$cap_appname-data:/opt/hub/data
      - $$cap_appname-conf:/opt/hub/conf
      - $$cap_appname-logs:/opt/hub/logs
      - $$cap_appname-backups:/opt/hub/backups
    caproverExtra:
      containerHttpPort: 8080
