captainVersion: "4"
caproverOneClickApp:
  description:
    "Datalore Enterprise is a self-hosted version of Datalore, tailored for teams that want to have a collaborative data
    science platform set up on their own infrastructure."
  instructions:
    start: Install jetrbains-datalore and start using it.
    end:
      You have to enable https prior to using $$cap_appname. You can then access it at
      https://$$cap_appname.$$cap_root_domain
  variables:
    - id: $$cap_app_version
      description:
        Version tag of jetrbains-datalore. See https://hub.docker.com/r/jetrbains-datalore/jetrbains-datalore/tags for a
        list of available versions.
      defaultValue: 2023.1
      label: App Version
    - id: $$cap_db_pass
      label: database password
      defaultValue: $$cap_gen_random_hex(16)
      description: Password for the database user and root using mysql.
  displayName: JetBrauns Datalore Enterprise
  isOfficial: false
  documentation: "https://www.jetbrains.com/help/datalore/"
services:
  $$cap_appname:
    image: jetbrains/datalore-server:$$cap_app_version
    volumes:
      - "$$cap_appname-datalore-storage:/opt/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DATALORE_PUBLIC_URL: https://$$cap_appname.$$cap_root_domain
      DB_PASSWORD: $$cap_db_pass
      DATABASES_DOCKER_NETWORK: captain-overlay-network
      SQL_SESSION_DOCKER_NETWORK: captain-overlay-network
    caproverExtra:
      containerHttpPort: "8080"
  $$cap_appname-postgresql:
    image: jetbrains/datalore-postgres:$$cap_app_version
    volumes:
      - "$$cap_appname-postgresql-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: $$cap_db_pass
    caproverExtra:
      notExposeAsWebApp: "true"
