captainVersion: "4"
caproverOneClickApp:
  description: "Jitsu is an open source high-performance data collection service."
  instructions:
    start: Install jitsu and start using it.
    end: Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of jitsu. See https://hub.docker.com/r/jitsucom/jitsu/tags
      defaultValue: 1.43.2
      label: App Version
  displayName: jitsu
  isOfficial: false
  documentation: "https://jitsu.com/docs"
services:
  $$cap_appname:
    image: jitsucom/jitsu:$$cap_app_version
    volumes:
      - $$cap_appname-data:/data/jitsu
    environment:
      REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379
      USER_RECOGNITION_REDIS_URL: redis://srv-captain--$$cap_appname-redis-users-recognition:6379
      USER_RECOGNITION_ENABLED: true
      TERM: xterm-256color
    caproverExtra:
      containerHttpPort: "8000"
  $$cap_appname-redis:
    image: redis:alpine
    volumes:
      - $$cap_appname-redis-data:/data
    restart: always
    caproverExtra:
      notExposeAsWebApp: "true"
  $$cap_appname-redis-users-recognition:
    image: redis:alpine
    volumes:
      - $$cap_appname-redis-users-recognition-data:/data
    restart: always
    caproverExtra:
      notExposeAsWebApp: "true"
