captainVersion: "4"
caproverOneClickApp:
  description:
    "Kinto is a minimalist JSON storage service with synchronisation and sharing abilities. It is meant to be easy to
    use and easy to self-host."
  instructions:
    start: "Install Kinto Server"
    end: "Have fun"
  variables:
    - id: $$cap_kinto_version
      label: Kinto Version Tag
      defaultValue: 14.3.0
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/kinto/kinto-server/tags
    - id: $$cap_postgres_version
      label: Postgres Version Tag
      defaultValue: 14
      description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres?tab=tags
    - id: $$cap_db_pass
      label: database password
      defaultValue: $$cap_gen_random_hex(16)
      description: Password for the database user and root using mysql.
      validRegex: /.{1,}/
    - id: $$cap_db_user
      label: database user
      defaultValue: postgres
      description: Username for the database using postgres.
      validRegex: /^([a-z0-9])+$/i
  displayName: kinto
  isOfficial: false
  documentation: "https://docs.kinto-storage.org/en/latest"
services:
  $$cap_appname-db:
    image: postgres:$$cap_postgres_version
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: $$cap_db_pass
      POSTGRES_PASSWORD: $$cap_db_pass
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: "true"
  $$cap_appname-cache:
    image: memcached:1
    caproverExtra:
      notExposeAsWebApp: "true"
  $$cap_appname:
    image: kinto/kinto-server:$$cap_kinto_version
    depends_on:
      - db
      - cache
    volumes:
      - $$cap_appname-config:/etc/kinto
    caproverExtra:
      containerHttpPort: "8888"
    environment:
      KINTO_CACHE_BACKEND: kinto.core.cache.memcached
      KINTO_CACHE_HOSTS: srv-captain--$$cap_appname-cache:11211 srv-captain--$$cap_appname-cache:11212
      KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
      KINTO_STORAGE_URL: postgresql://$$cap_db_pass:$$cap_db_pass@srv-captain--$$cap_appname-db/postgres
      KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
      KINTO_PERMISSION_URL: postgresql://$$cap_db_pass:$$cap_db_pass@srv-captain--$$cap_appname-db/postgres
