captainVersion: "4"
caproverOneClickApp:
  description: "An open-source, self-hosted memo hub with knowledge management and socialization"
  instructions:
    start: Install memos and start using it.
    end: Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of memos. See https://hub.docker.com/r/neosmemo/memos/tags?page=1&ordering=last_updated for available versions.
      defaultValue: 0.10.0
      label: App Version
  displayName: memos
  isOfficial: false
  documentation: "https://github.com/usememos/memos"
services:
  $$cap_appname:
    image: neosmemo/memos:$$cap_app_version
    volumes:
      - $$cap_appname-data:/var/opt/memos
    environment: []
    caproverExtra:
      containerHttpPort: "5230"
