captainVersion: "4"
caproverOneClickApp:
  description:
    "MetaTube downloads video from YouTube and can add metadata from a specified metadata provider on the downloaded
    file."
  instructions:
    start: "Simply install the program"
    end: "Have fun"
  variables:
    - id: $$cap_metatube_version
      label: Metatube Image Version
      defaultValue: latest
      validRegex: /^([^\s^\/])+$/

  displayName: metatube
  isOfficial: false
  documentation: "https://github.com/JVT038/MetaTube"
services:
  $$cap_appname:
    restart: always
    image: jvt038/metatube:latest
    volumes:
      - $$cap_appname-downloads:/downloads
      - $$cap_appname-metatube:/database
    caproverExtra:
      containerHttpPort: "5000"
