# @format

captainVersion: 4

caproverOneClickApp:
  variables:
    - id: "$$cap_tz"
      label: Time Zone
      defaultValue: Europe/Berlin
      description: Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      validRegex: "/.{1,}/"
    - id: $$cap_claim_url
      label: Claim URL
      defaultValue: "https://app.netdata.cloud"
      description: The URL to your Captain instance
      validRegex: "/.{1,}/"
    - id: $$cap_claim_token
      label: Claim Token
      defaultValue: "YOUR_CLAIM_TOKEN"
      description: The token to your Captain instance
      validRegex: "/.{1,}/"
    - id: $$cap_claim_room
      label: Claim Room
      defaultValue: "YOUR_CLAIM_ROOM"
      description: The room to your Captain instance
      validRegex: "/.{1,}/"
  instructions:
    start: |-
      Running the Netdata Agent in a container works best for an internal network or to quickly analyze a host. Docker helps you get set up quickly, and doesn't install anything permanent on the system, which makes uninstalling the Agent easy.

    end: |-
      netdata has been successfully deployed!
  displayName: "netdata (ARM)"
  isOfficial: false
  description: "The open-source, real-time, performance and health monitoring."
  documentation: See https://learn.netdata.cloud/docs/

services:
  netdata:
    image: netdata/netdata
    hostname: $$cap_appname.$$cap_root_domain
    ports:
      - 19999:19999
    caproverExtra:
      containerHttpPort: "19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - $$cap_appname-netdata-config:/etc/netdata
      - $$cap_appname-netdata-lib:/var/lib/netdata
      - $$cap_appname-netdata-cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      NETDATA_CLAIM_TOKEN: $$cap_claim_token
      NETDATA_CLAIM_URL: $$cap_claim_url
      NETDATA_CLAIM_ROOMS: $$cap_claim_room
