captainVersion: 4
services:
  "$$cap_appname":
    image: nocodb/nocodb:$$cap_version
    restart: always
    environment:
      NC_DB: "pg://srv-captain--$$cap_appname-db:5432?u=$$cap_dbuser&p=$$cap_dbpass&d=$$cap_dbname"
      NC_PUBLIC_URL: "https://$$cap_appname.$$cap_root_domain"
      NC_AUTH_JWT_SECRET: $$cap_auth_jwt_secret
      NC_SENTRY_DSN: $$cap_sentry_dsn
      NC_DISABLE_TELE: 1
      NC_REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379/0
      NC_SMTP_HOST: $$cap_smtp_host
      NC_SMTP_FROM: $$cap_smtp_from
      NC_SMTP_PORT: $$cap_smtp_port
      NC_SMTP_USERNAME: $$cap_smtp_username
      NC_SMTP_PASSWORD: $$cap_smtp_password
      NC_SMTP_IGNORE_TLS: $$cap_smtp_ignore_tls
      NC_SMTP_SECURE: $$cap_smtp_secure
      NC_GOOGLE_CLIENT_ID: $$cap_google_client_id
      NC_GOOGLE_CLIENT_SECRET: $$cap_google_client_secret
    volumes:
      - "$$cap_appname-data:/usr/app/data"
    caproverExtra:
      containerHttpPort: "8080"
  $$cap_appname-db:
    image: postgres:$$cap_postgres_version
    environment:
      POSTGRES_DB: $$cap_dbname
      POSTGRES_USER: $$cap_dbuser
      POSTGRES_PASSWORD: $$cap_dbpass
    volumes:
      - $$cap_appname-db:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: "true"
  $$cap_appname-redis:
    image: redis:7
    volumes:
      - $$cap_appname-redis:/data
    caproverExtra:
      notExposeAsWebApp: "true"
caproverOneClickApp:
  variables:
    - id: "$$cap_version"
      label: NocoDB Version
      defaultValue: "0.101.0"
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/nocodb/nocodb/tags
    - id: "$$cap_auth_jwt_secret"
      label: NC_AUTH_JWT_SECRET
      defaultValue: "$$cap_gen_random_hex(64)"
      description: "JWT secret used for auth and storing other secrets. If absent: A Random secret will be generated"
    - id: "$$cap_sentry_dsn"
      label: NC_SENTRY_DSN
      defaultValue: ""
      description: For Sentry monitoring
    - id: $$cap_postgres_version
      label: Postgres Version. See tags https://hub.docker.com/_/postgres for valid values
      defaultValue: "15"
      description: Checkout their page for the valid tags https://hub.docker.com/_/postgres
      validRegex: /^([^\s^\/])+$/
    - id: $$cap_dbname
      label: Database Name
      defaultValue: "postgres"
    - id: $$cap_dbuser
      label: Database User
      defaultValue: "user"
    - id: $$cap_dbpass
      label: Potgress Database password
      description: "Password for postgres"
      defaultValue: $$cap_gen_random_hex(16)
    - id: $$cap_smtp_from
      label: NC_SMTP_FROM
      description: "Email address to send emails from"
    - id: $$cap_smtp_host
      label: NC_SMTP_HOST
      description: "SMTP host"
    - id: $$cap_smtp_port
      label: NC_SMTP_PORT
      description: "SMTP port"
      defaultValue: "587"
    - id: $$cap_smtp_username
      label: NC_SMTP_USER
      description: "SMTP user"
    - id: $$cap_smtp_password
      label: NC_SMTP_PASSWORD
      description: "SMTP password"
    - id: $$cap_smtp_secure
      label: NC_SMTP_SECURE
      description: "To enable secure set value as true any other value treated as false"
      defaultValue: "false"
    - id: $$cap_smtp_ignore_tls
      label: NC_SMTP_IGNORE_TLS
      description:
        "To ignore tls set value as true any other value treated as false. For more info visit
        https://nodemailer.com/smtp/"
      defaultValue: "false"
    - id: $$cap_google_client_id
      label: NC_GOOGLE_CLIENT_ID
      description: Google client id to enable google authentication
    - id: $$cap_google_client_secret
      label: NC_GOOGLE_CLIENT_SECRET
      description: "Google client secret to enable google authentication"
  instructions:
    start:
      "NocoDB is an open source #NoCode platform that turns any database into a smart spreadsheet.
      https://github.com/nocodb/nocodb - https://www.nocodb.com/"
    end:
      NocoDB has been successfully deployed! It might take a minute or two to boot though, during which time you might
      get a 502
  displayName: NocoDB
  isOfficial: true
  description:
    The Open Source Airtable Alternative - Turns any MySQL, PostgreSQL, SQL Server, SQLite & MariaDB into a
    smart-spreadsheet.
  documentation: See https://github.com/nocodb/nocodb
