captainVersion: "4"
caproverOneClickApp:
  description: "Self-hosted Git Server with CI/CD and Kanban. Check https://github.com/theonedev/onedev for details"
  instructions:
    start: Install onedev and start using it.
    end: Remeber to map Ports 6610 and 6611 to use onedev. Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of onedev. See https://hub.docker.com/r/1dev/server/tags/ for more information.
      defaultValue: 7.3.12
      label: App Version
  displayName: onedev
  isOfficial: false
  documentation: ""
services:
  $$cap_appname:
    image: onedev:$$cap_app_version
    volumes:
      - $$cap_appname-data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    caproverExtra:
      containerHttpPort: "6610"
