# @format

captainVersion: 4
services:
  $$cap_appname:
    image: "rabbitcompany/passky-database:$$cap_passky_version"
    restart: unless-stopped
    environment:
      #
      # Change environment variables in .env file
      # You can also run an installer.sh that would auto generate .env file
      # or run installerGUI.sh for graphical configuration.
      #
      # Database

      - MYSQL_DATABASE: $$cap_db_database
      - MYSQL_USER: $$cap_db_user
      - MYSQL_PASSWORD: $$cap_db_pass
      - MYSQL_ROOT_PASSWORD: $$cap_db_pass
      # Backup
      - BACKUP_ENABLED: $$cap_backup_enabled
      - BACKUP_HOST: $$cap_backup_host
      - BACKUP_PORT: $$cap_backup_port
      - BACKUP_USER: $$cap_backup_user
      - BACKUP_PASSWORD: $$cap_backup_pass
      - BACKUP_LOCATION: $$cap_backup_location
    volumes:
      - $$cap_appname-db-data:/var/lib/mysql
  $$cap_appname-api:
    container_name: passky-api
    image: "rabbitcompany/passky-api:latest"
    restart: unless-stopped
    environment:
      #
      # Change environment variables in .env file
      # You can also run an installer.sh that would auto generate .env file
      # or run installerGUI.sh for graphical configuration.
      #
      # Server
      - SERVER_LOCATION: $$cap_server_location
      # Database
      - MYSQL_DATABASE: $$cap_db_database
      - MYSQL_USER: $$cap_db_user
      - MYSQL_PASSWORD: $$cap_db_pass
      - MYSQL_ROOT_PASSWORD: $$cap_db_pass
      # Mail
      - MAIL_ENABLED
      - MAIL_HOST: $$cap_email_host
      - MAIL_PORT: $$cap_email_port
      - MAIL_USERNAME: $$cap_email_user
      - MAIL_PASSWORD: $$cap_email_pass
      - MAIL_USE_TLS: $$cap_email_tls

      # Account
      - ACCOUNT_MAX: $$cap_account_max
      - ACCOUNT_MAX_PASSWORDS: $$cap_account_max_passwords
      # YUBICO
caproverOneClickApp:
  variables:
    - id: $$cap_passky_version
      label: passky Version Tag
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/library/passky/tags/
      defaultValue: "latest"
    - id: $$cap_db_database
      label: Database name
      defaultValue: passky
      description: Nmae of my MySQL db
    - id: $$cap_db_pass
      label: MySQL Root password
      description: "Root password that will be created on MySQL"
      defaultValue: $$cap_gen_random_hex(16)
    - id: $$cap_db_user
      label: Database user
      description: Database user
      defaultValue: passky
      validRegex: "/^([a-zA-Z0-9])+$/"
    - id: $$cap_server_location
      label: Server location
      description: "Server location (e.g. https://passky.example.com)"
      defaultValue: "https://passky.example.com"
      validRegex: "/^([a-zA-Z0-9-.])*$/"
    - id: $$cap_email_enabled
      label: "Enable Email"
      description: "Enable Email"
      defaultValue: false
    - id: $$cap_email_host
      label: Email SMTP Server
      description: "Host used as smtp server. More info: https://help.passbolt.com/configure/email/setup."
    - id: $$cap_email_port
      label: Email SMTP Port
      description: "Port used with the smtp server. More info: https://help.passbolt.com/configure/email/setup"
    - id: $$cap_email_user
      label: Email Username
    - id: $$cap_email_pass
      label: Email Password
    - id: $$cap_email_tls
      label: TLS Enabled
      defaultValue: "true"
    - id: $$cap_account_max
      label: Max accounts
      description: "Maximum number of accounts allowed"
      defaultValue: "100"
    - id: $$cap_account_max_passwords
      label: Max passwords per account
      description: "Maximum number of passwords per account"
      defaultValue: "1000"
  isOfficial: false
  caproverExtra:
    containerHttpPort: "8000"
  displayName: Passky
  description: "A password manager for your team"
  instructions:
    start: Install
    end: "You can now access your Passky instance at http://$$cap_appname.$$cap_root_domain"
