captainVersion: 4
version: "3"
services:
  $$cap_appname-db:
    restart: unless-stopped
    image: questdb/questdb:$$cap_questdb_version
    volumes:
      - $$cap_appname-db-data:/var/lib/questdb
    environment:
      QDB_HTTP_BIND_TO: $$cap_qdb_http_bind_to
    caproverExtra:
      containerHttpPort: "9000"
      notExposeAsWebApp: "true"
caproverOneClickApp:
  variables:
    - id: $$cap_questdb_version
      label: QuestDB Version
      defaultValue: "6.6.1"
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/questdb/questdb/tags
      validRegex: /^([^\s^\/])+$/
    - id: $$cap_qdb_http_bind_to
      label: QuestDB Web Console Port
      defaultValue: "9000"
  instructions:
    end: >
      QuestDB is a relational column-oriented database designed for time series and event data. It uses SQL with extensions for time series to assist with real-time analytics. These pages cover core concepts of QuestDB, including setup steps, usage guides, and reference documentation for syntax, APIs and configuration.
      More ENVIRONMENT VARIABLES can be found at: https://questdb.io/docs/reference/configuration#environment-variables-1
    start: QuestDB is the fastest open source time series database
  displayName: QuestDB
  isOfficial: true
  description: Fast SQL for time series
  documentation: https://github.com/ml-tooling/ml-workspace
