captainVersion: 4
caproverOneClickApp:
  isOfficial: false
  displayName: "rdiffweb"
  description: "rdiffweb is a web application for comparing files"
  instructions:
    start: Install rdiffweb.
    end: rdiffweb is deployed.
  variables:
    - id: $$cap_rdiffweb_version
      label: rdiffweb Version
      defaultValue: "latest"
      description: Checkout their docker page for the valid tags https://hub.docker.com/r/alexta69/rdiffweb/tags
    - id: $$cap_rdiffweb_disable_ssh_keys
      label: Disable SSH Keys
      defaultValue: 1
      description: Disable SSH keys for rdiffweb

version: "3.5"
services:
  rdiffweb:
    image: ikus060/rdiffweb:$$cap_rdiffweb_version
    container_name: rdiffweb
    caproverExtra:
      containerHttpPort: 8080
    volumes:
      - $$cap_appname-backups:/backups
      - $$cap_appname-config:/etc/rdiffweb
      - $$cap_appname-sessions:/var/lib/rdiffweb/session
      - $$cap_appname-restores:/restores
    restart: "unless-stopped"
    environment:
      - RDIFFWEB_TEMPDIR=/restores
      - RDIFFWEB_SESSION_DIR=/var/lib/rdiffweb/session
      - RDIFFWEB_DISABLE_SSH_KEYS=$$cap_rdiffweb_disable_ssh_keys
