captainVersion: 4

services:
  $$cap_appname:
    image: ghcr.io/go-shiori/shiori:$$cap_app_version
    environment:
      SHIORI_DIR: /data
      SHIORI_DBMS: postgresql
      SHIORI_PG_USER: $$cap_dbuser
      SHIORI_PG_PASS: $$cap_dbpass
      SHIORI_PG_DB: $$cap_dbname
      SHIORI_PG_HOST: srv-captain--$$cap_appname-db
      SHIORI_PG_PORT: 5432
    volumes:
      - $$cap_appname-shiori-data:/data
    restart: on-failure
    caproverExtra:
      containerHttpPort: "8080"
  $$cap_appname-db:
    image: postgres:$$cap_postgres_version
    environment:
      POSTGRES_DB: $$cap_dbname
      POSTGRES_USER: $$cap_dbuser
      POSTGRES_PASSWORD: $$cap_dbpass
    volumes:
      - $$cap_appname-db:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: "true"
caproverOneClickApp:
  variables:
    - id: $$cap_app_version
      label: App Version
      defaultValue: "1.5.3"
      description: "See https://github.com/go-shiori/shiori/pkgs/container/shiori"
    - id: $$cap_postgres_version
      label: Postgres Version
      defaultValue: "13"
    - id: $$cap_dbname
      label: Database Name
      defaultValue: "postgres"
      validRegex: /^([^\s^\/])+$/
    - id: $$cap_dbuser
      label: Database User
      defaultValue: "user"
      validRegex: /^([^\s^\/])+$/
    - id: $$cap_dbpass
      label: Database Password
      defaultValue: $$cap_gen_random_hex(64)
      validRegex: /^([^\s^\/])+$/
  isOfficial: false
  displayName: "Shiori (ARM)"
  description: "A simple bookmark manager built with Go."
  instructions:
    start: >
      This app stores its data in a SQLite database in a Docker volume.

      Once deployed, this app will be accessible with a default username and
      password. If this is a problem, you should deploy behind TLS and
      basic-auth until you can log in and change them.

      username: shiori

      password: gopher
    end: >
      Shiori is up and running.

      You can log in with the username and password below to  create and account
      under `Settings`. Once you've created an account the default credentials
      will be disabled.

      username: shiori

      password: gopher
    documentation: >
      From https://github.com/go-shiori/shiori.
