captainVersion: "4"
caproverOneClickApp:
  description: "An opensource kubernetes based serverless platform with built-in security and instant GraphQL APIs for any database and microservice"
  instructions:
    start: Install spacecloud and start using it.
    end: Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of spacecloud
      defaultValue: latest
      label: App Version
    - cluster_id: $$cap_cluster_id
      description: Cluster ID
      defaultValue: "prod-cluster"
      label: Cluster ID
    - admin_user: $$cap_admin_user
      description: Admin User
      defaultValue: "admin"
      label: Admin User
    - admin_pass: $$cap_admin_pass
      description: Admin Password
      defaultValue: $$cap_gen_random_hex(16)
      label: Admin Password
    - admin_secret: $$cap_admin_secret
      description: Admin Secret
      defaultValue: $$cap_gen_random_hex(16)
      label: Admin Secret
    - gateway_version: $$cap_gateway_version
      description: Gateway Version
      defaultValue: 0.21.5
      label: Gateway Version
    - debezium_version: $$cap_debezium_version
      description: Debezium Version
      defaultValue: 0.2.0
      label: Debezium Version
    - id: $$cap_postgres_version
      label: Postgres (database) version
      defaultValue: "15"
      description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres?tab=tags
    - id: $$cap_db_db
      label: database name
      defaultValue: authentik
      description: Name of the database.
    - id: $$cap_db_pass
      label: database password
      defaultValue: $$cap_gen_random_hex(16)
      description: Password for the database user and root using mysql.
      validRegex: /.{1,}/
  displayName: spacecloud
  isOfficial: false
  documentation: "https://docs.space-cloud.io"
services:
  $$cap_appname-gateway:
    image: spacecloudio/gateway:$$cap_gateway_version
    caproverExtra:
      containerHttpPort: "4122"
    environment:
      DEV: true # Turn this to false for production mode
      CLUSTER_ID: $$cap_cluster_id
      CONFIG: /config/config.yaml
      ADMIN_USER: $$cap_admin_user # Log in username
      ADMIN_PASS: $$cap_admin_pass # Log in password
      ADMIN_SECRET: $$cap_admin_secret
      LOG_LEVEL: debug # other values info, warn
      LOG_FORMAT: json # other values text
      DISABLE_UI: false
      LETSENCRYPT_STORE: local
      REDIS_CONN: srv-captain--$$cap_appname-redis:6379
      SSL_ENABLE: false
      SSL_CERT: ""
      SSL_KEY: ""
    volumes:
      - $$cap_appname-gateway-config:/config
  $$cap_appname-redis:
    image: redis:7
    restart: always
  $$cap_appname-debezium:
    image: "spacecloudio/dbevents:$$cap_debezium_version"
    environment:
      SC_ADMIN_SECRET: $$cap_admin_secret
      GATEWAY_URL: srv-captain--$$cap_appname-gateway:4122
    depends_on:
      - $$cap_appname-gateway
      - $$cap_appname-postgres
  $$cap_appname-postgres:
    image: "postgres:$$cap_postgres_version" # other values never, if_not_present
    restart: "always" # other values no, on-failure
    environment:
      POSTGRES_PASSWORD: $$cap_db_pass
      POSTGRES_DB: $$cap_db_db
      POSTGRES_USER: $$cap_db_user
    volumes:
      - sc-postgres-data:/var/lib/postgresql/data
