captainVersion: "4"
caproverOneClickApp:
  description: "Thin Backend is a blazing fast, universal web app backend for making realtime single page apps. Delight your end-users with superior speed and lowest latency."
  instructions:
    start: Install thin.dev and start using it.
    end: Have fun!
  variables:
    - id: $$cap_app_version
      description: Version of thin.dev
      defaultValue: latest
      label: App Version
    - id: $$cap_postgres_version
      label: Postgres Version
      defaultValue: "alpine3.16"
      description: Checkout their page for the valid tags https://hub.docker.com/_/postgres
      validRegex: /^([^\s^\/])+$/
  displayName: thin.dev
  isOfficial: false
  documentation: ""
services:
  $$cap_appname:
    image: downloads.digitallyinduced.com/digitallyinduced/thin-backend:$$cap_app_version
    volumes:
      - $$cap_appname-data:/home/app/Application:rw
    environment:
      DATABASE_URL: postgresql://thin:thin@srv-captain--$$cap_appname-postgres/thin
      TYPE_DEFINIIONS_BASE_PATH: $$cap_appname-data
    depends_on:
      - $$cap_appname-postgres
    caproverExtra:
      containerHttpPort: "8000"
  $$cap_appname-postgres:
    image: postgres:$$cap_postgres_version
    volumes:
      - $$cap_appname-postgres-data:/var/lib/postgresql/data
    restart: always

    environment:
      POSTGRES_DB: thin
      POSTGRES_USER: thin
      POSTGRES_PASSWORD: thin
    caproverExtra:
      notExposeAsWebApp: "true"
