captainVersion: "4"
caproverOneClickApp:
  description:
    "Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases."
  instructions:
    start: "Install Trilium Notes"
    end: "Happy using Trilium Notes!"
  variables:
    - id: $$cap_trilium_version
      label: Trilium Version
      defaultValue: "latest"
      validRegex: /^([a-zA-Z0-9])+$/

  displayName: trilium
  isOfficial: false
  documentation: https://github.com/zadam/trilium/wiki/
services:
  $$cap_appname:
    image: zadam/trilium:$$cap_trilium_version
    volumes:
      - $$cap_appname-config:/data
    environment:
      TRILIUM_DATA_DIR: /data
    caproverExtra:
      containerHttpPort: 8080
