captainVersion: 4
services:
  # Webtop
  $$cap_appname:
    image: ghcr.io/linuxserver/webtop:$$cap_webtop_version
    restart: unless-stopped
    environment:
      TZ: $$cap_tz
      PUID: $$cap_puid
      PGID: $$cap_guid
    volumes:
      - $$cap_appname-config:/config
    caproverExtra:
      containerHttpPort: "3000"
caproverOneClickApp:
  variables:
    - id: $$cap_webtop_version
      label: Webtop Version
      defaultValue: latest
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/linuxserver/webtop/tags

    - id: $$cap_tz
      label: Timezone
      description: This is the timezone for the application, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      defaultValue: Europe/Brussels

    - id: $$cap_puid
      label: User ID
      defaultValue: "1000"
      description: User ID that the process uses, run (id $user) in your instance to see the id

    - id: $$cap_guid
      label: Group ID
      defaultValue: "1000"
      description: Group ID that the process uses, run (id $user) in your instance to see the id
  instructions:
    start: |-
      Webtop - Alpine and Ubuntu based containers containing full desktop environments in officially supported flavors accessible via any modern web browser.
      Pls read more at https://github.com/linuxserver/docker-webtop

      This image provides various versions that are available via tags.
      latest tag usually provides the latest stable version.
      Others are considered under development and caution must be exercised when using them.

      https://github.com/linuxserver/docker-webtop#version-tags
      Tag	Description
      latest	XFCE Alpine
      ubuntu-xfce	XFCE Ubuntu
      alpine-kde	KDE Alpine
      ubuntu-kde	KDE Ubuntu
      alpine-mate	MATE Alpine
      ubuntu-mate	MATE Ubuntu
      alpine-i3	i3 Alpine
      ubuntu-i3	i3 Ubuntu
      alpine-openbox	Openbox Alpine
      ubuntu-openbox	Openbox Ubuntu
      alpine-icewm	IceWM Alpine
      ubuntu-icewm	IceWM Ubuntu

    end: |-
      Aaaand you're done! 😄
      Your service is available at http://$$cap_appname.$$cap_root_domain

      The default user/pass = abc/abc
  displayName: Webtop
  isOfficial: true
  description: 🚀 Ubuntu and Alpine based Webtop images, Linux in a web browser supporting popular desktop environments.
  documentation: Taken from https://github.com/linuxserver/docker-webtop
