captainVersion: "4"
caproverOneClickApp:
  description:
    "WireGuard® is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to
    be faster, simpler, leaner."
  instructions:
    start: Install wireguard-vpn and start using it.
    end: $$cap_app_name is now installed and available at $$cap_appname.$$cap_root_domain
  variables:
    - id: $$cap_app_version
      description:
        Version tag of wireguard-vpn. See https://hub.docker.com/r/wireguard-vpn/wireguard-vpn/tags for a list of
        available versions.
      defaultValue: latest
      label: App Version
    - id: $$cap_tz
      description: Timezone to use for the app.
      defaultValue: Europe/Berlin
      label: Timezone
    - id: $$cap_wg_peers
      description: Number of peers to create.
      defaultValue: 10
      label: Number of peers
    - id: $$cap_wg_serverurl
      description: Server URL to use for the app.
      defaultValue: $$cap_appname.$$cap_root_domain
      label: Server URL
    - id: $$cap_wg_serverport
      description: Server port to use for the app.
      defaultValue: $$cap_wg_serverurl
      label: Server Port
    - id: $$cap_wg_peerdns
      description:
        "DNS server set in peer/client configs (can be set as 8.8.8.8). Used in server mode. Defaults to auto, which
        uses wireguard docker host's DNS via included CoreDNS forward."
      defaultValue: auto
      label: Peer DNS
    - id: $$cap_wg_internal_subnet
      description:
        Internal subnet for the wireguard and server and peers (only change if it clashes). Used in server mode.
    - id: $$cap_wg_allowedips
      description:
        "The IPs/Ranges that the peers will be able to reach using the VPN connection. If not specified the default
        value is: '0.0.0.0/0, ::0/0' This will cause ALL traffic to route through the VPN, if you want split tunneling,
        set this to only the IPs you would like to use the tunnel AND the ip of the server's WG ip, such as 10.13.13.1."
      defaultValue: 0.0.0.0/0
      label: Allowed IPs
    - id: $$cap_wg_persistentkeepalive_peers
      description: "PersistentKeepalive for peers (comma separated). Used in server mode."
      label: PersistentKeepalive for peers
    - id: $$cap_wg_log_confs
      description: "Log the generated configs to the container log. Used in server mode."
      defaultValue: "true"
      label: Log the generated configs
  displayName: wireguard-vpn
  isOfficial: false
  documentation: ""
services:
  $$cap_appname:
    image: lscr.io/linuxserver/wireguard:$$cap_app_version
    conainername: $$cap_appname
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules #optional
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - SERVERURL=$$cap_appname.$$cap_root_domain #optional
      - SERVERPORT=$$cap_wg_serverurl #optional
      - PEERS=$$cap_wg_peers
      - PEERDNS=$$cap_wg_peerdns #optional
      - INTERNAL_SUBNET=$$cap_wg_internal_subnet #optional
      - ALLOWEDIPS=$$cap_wg_allowedips
      - PERSISTENTKEEPALIVE_PEERS=$$cap_wg_persistentkeepalive_peers #optional
      - LOG_CONFS=$$cap_wg_log_confs #optional
    hostname: $$cap_appname.$$cap_root_domain
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    caproverExtra:
      containerHttpPort: "$$cap_wg_serverurl"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
