version: "3"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  environment:
  - REDASH_SECRET_KEY=
  - REDASH_COOKIE_SECRET=
  - REDASH_DATABASE_URL=postgresql://postgres:password@postgres/postgres
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      - REDASH_WEB_WORKERS=4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      - QUEUES="celery"
      - WORKERS_COUNT=1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      - QUEUES="scheduled_queries,schemas"
      - WORKERS_COUNT=1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      - QUEUES="queries"
      - WORKERS_COUNT=2
  worker:
    <<: *redash-service
    command: worker
    environment:
      - QUEUES="periodic emails default"
      - WORKERS_COUNT=1
  redis:
    image: redis/redis-stack-server:7.0.2-RC4
    restart: always
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:15.1-bullseye
    environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
    postgres-data:
    redis-data:
